### ISSUE TITLE
Crash when trying to download/share images

### ISSUE THREAD

**Issue by cool00geek** [ccrama/Slide-iOS#201]
When an image is opened up by tapping on the image link or image directly for a post, the two buttons on the bottom right: the "menu" button (3 dots) and download button both result in the application crashing.

**Comment by ccrama** [comment]
What device and os? Thanks for the report

**Comment by cool00geek** [comment]
iPhone 6s running iOS 11.3.1

**Comment by ccrama** [comment]
Fixed, also implemented it for videos as well!

**Comment by cool00geek** [comment]
Today the rc1 for beta was released, and the 3dots near the images still crash the app. For example, when an image is opened, and the "menu button" (the 3 dots on the bottom right) is tapped, the app crashes (iPhone 6s, iOS 11.4). Download does work now though.

**Comment by ccrama** [comment]
Hmm I'm using a 6S and am not crashing when clicking the 3 dot menu. Do you have an example post that is causing this?

**Comment by cool00geek** [comment]
See [slide_shareBug_BetaRC1.mp4.zip](https://github.com/ccrama/Slide-iOS/files/2092717/slide_shareBug_BetaRC1.mp4.zip) for a screen video of the bug.

The posts I tapped on are these:
- https://www.reddit.com/r/aww/comments/8qep03/i_was_drunk_in_the_french_quarter_and_a_kind/
- https://www.reddit.com/r/EarthPorn/comments/8qes1y/stumbled_upon_this_trifecta_while_exploring/
