### ISSUE TITLE
Opening comment from profile page crashes the app

### ISSUE THREAD

**Issue by incIined** [ccrama/Slide-iOS#212]
iPhone SE 10.2.1, Slide 1.0.0 (13)

Video of the issue:

https://streamable.com/b5ycg

**Comment by ccrama** [comment]
Has been fixed

**Comment by incIined** [comment]
Still having the same issue on Slide 1.0.0 (14)

https://streamable.com/cab3u

**Comment by ccrama** [comment]
Build 14 was from a few days ago, have since fixed it and am awaiting build 15 approval!
