### ISSUE TITLE
Request: Allow control of font size for post titles in cards

### ISSUE THREAD

**Issue by colejd** [ccrama/Slide-iOS#248]
Hello!

Can we have an option for controlling the size of post titles in cards? Perhaps this is already implemented in "Submission font size", but I can't figure out what that is changing.

**Comment by colejd** [comment]
"Submission font size" does actually satisfy this request, but any changes you make don't get reflected until you restart the app.

**Comment by ccrama** [comment]
Should have been fixed, are you fully up to date on commits?

**Comment by colejd** [comment]
I think I was, but I just updated to make sure and the bug is still there. Everything but the title changes size until you restart the app.

**Comment by ccrama** [comment]
Fixed
