### ISSUE TITLE
Remove very white and black colors from the color pool for subreddit accent colors

### ISSUE THREAD

**Issue by colejd** [ccrama/Slide-iOS#324]
The subreddit color picking algorithm should only match to material colors from 400 to 700. That will ensure that the colors chosen don't conflict with lighter or darker themes.

**Comment by ccrama** [comment]
Done, have pruned a lot of colors out and made all accents/main colors readable. Also took out gray from the auto-coloring system choices

**Comment by colejd** [comment]
Sorry to reopen this, but I'm still getting some darker colors. It looks in that commit that a lot of 800/900 color variants are still available.

**Comment by ccrama** [comment]
I don't think it's worth removing those colors, I tested them on black and they were still readable. Maybe some of the dark blue ones could be removed but the colored ones are okay imo

**Comment by ccrama** [comment]
I don't think this is an issue anymore
