### ISSUE TITLE
When a post is hidden, it says Hidden Forever, but they come back when the screen is refreshed.

### ISSUE THREAD

**Issue by cagriuslu** [ccrama/Slide-iOS#405]
Happens on iPhone SE.

**Comment by ccrama** [comment]
Fixed!

**Comment by WickedColdfront** [comment]
@ccrama I’m still seeing this problem on 1.1 build 45. 

Hiding a post makes it go away and the post shows up in hidden posts, but the post shows up again as soon as I refresh.

**Comment by ccrama** [comment]
It is fixed for v1.2. The hiding code worked, but I told Reddit in the
headers to return all content whether or not it was hidden (you can still
see it on the hidden section of your profile)
