### ISSUE TITLE
Crashing on iPad Pro (2016)

### ISSUE THREAD

**Issue by scot-onet** [ccrama/Slide-iOS#701]
Crashes after scrolling for a few minutes.  No specific pages or Subreddits cause the issue.  

Cleared cache without luck. Reinstalled without luck. 

iOS fully updated and no other device issues. 

Crashing starts with application stuttering and heating of device.

**Comment by colejd** [comment]
Could you please try setting video autoplay to "Never autoplay videos"? We've identified a potential memory leak relating to videos that we're in the process of fixing, and I'd like to see if that resolves your problem.

**Comment by scot-onet** [comment]
Still crashes. May be able to scroll further, but it still ends with stuttering, black screen and back to the home screen/out of the app.

**Comment by ccrama** [comment]
Do you experience this if you reset to default settings?

**Comment by scot-onet** [comment]
Yes.  Only thing I have changed is the theme is the Oled black one.  I’ll reset it again to default later to make sure it’s all clean and clear.

**Comment by colejd** [comment]
How are things since 2.1.2? We found and squished a few bugs relating to video players leaking memory.

**Comment by scot-onet** [comment]
Confirmed it still crashes. Both on an older 9.7 and 12.9 iPP.  It seems to take more scrolling,  it that’s a bit unscientific...

**Comment by scot-onet** [comment]
What can i do to help?

**Comment by ccrama** [comment]
A lot has been done for v3.0 and I think the memory issue you were seeing has been fixed. If you notice anything else please re-open the issue!

**Comment by scot-onet** [comment]
Not sure how to reopen.  It is SIGNIFICANTLY better, so it does appear great progress has been made, but I do still have some crashing issues.  In the case of a crash a few minutes ago i was able to browse for 45 minutes straight with lots of gifs etc showing up before it just stopped responding.  After about 30-45 seconds The app crashed.

Had this happen a few times over the past week.  

Again though, great progress!

**Comment by ccrama** [comment]
Unfortunately random crashes like that are much harder to reproduce any may not be fixable without some steps for reproduction. Let me know if you find any! That is likely a completely different issue then what we’ve fixed
