### ISSUE TITLE
Show full links in submission page and link action menu

### ISSUE THREAD

**Issue by colejd** [ccrama/Slide-iOS#778]

**Comment by ccrama** [comment]
Done in 3.0 already

**Comment by colejd** [comment]
Not so, friendo. I guess I forgot to paste the link to the request, so lemme clarify:
- The submission VC doesn't let the link field grow. This is still present in the latest master.
- In the link action menu, the link is limited to one line in the top menu. We should let this grow, or maybe marquee it somehow?

**Comment by ccrama** [comment]
Is this relevant with my changes to the bottom menu in v4.0?
